# Generated by Django 4.1.2 on 2022-10-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(choices=[('ATLANTA', 'Atlanta'), ('DENVER', 'Denver')], default='ATLANTA', max_length=50, verbose_name='location'),
        ),
    ]
