# Generated by Django 4.1.2 on 2022-10-13 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date_of_event',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
