# Generated by Django 4.1.2 on 2022-10-13 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_request_date_of_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['date_of_event']},
        ),
        migrations.AddField(
            model_name='request',
            name='chef',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='main_app.chef'),
        ),
    ]
