# Generated by Django 4.1.2 on 2022-10-14 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_request_options_request_chef'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('chef', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main_app.chef')),
                ('name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.client')),
            ],
        ),
    ]
