# Generated by Django 4.1.2 on 2022-10-16 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chef', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chatrooms', to='main_app.chef')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.client')),
            ],
        ),
    ]
