# Generated by Django 4.1.2 on 2022-10-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_delete_chatroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(default='bio', max_length=500, verbose_name='bio'),
        ),
    ]
