# Generated by Django 4.1.2 on 2022-10-17 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_rename_profile_pic_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
